const {test}=require('node:test');const assert=require('node:assert/strict');
const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');
const {HeadlessRuntime}=require('../runtime/headless-runtime.cjs');
const {RemoteServer}=require('../server/http.cjs');
const token='a'.repeat(64);
test('authenticated remote session: ingest dedupe, anchored FIFO, targeted cancel, pause/resume',async t=>{
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'tvlens-remote-test-'));let finishFirst;let clock=0;
 const first=new Promise(resolve=>finishFirst=resolve);let started;
 const invoked=new Promise(resolve=>started=resolve);
 const agent={answer:async({question,signal})=>{started();if(question==='first')await Promise.race([first,new Promise(r=>signal.addEventListener('abort',r,{once:true}))]);return {answer:question,kind:'explanation',citations:[],limits:[]};}};
 const runtime=new HeadlessRuntime({userData:dir,sessionsRoot:path.join(dir,'sessions'),config:{},selectedModels:{observationModel:'test',inspectionModel:'test',codexModel:'test'},smoke:true,agent,readClock:()=>clock});
 let assemblies=0;const media={assemble:async x=>{assemblies++;return {...x,clip:Buffer.from('fixture'),frames:[{atMs:x.startMs,dataUrl:'data:image/jpeg;base64,YQ=='}],audio:null};}};
 const server=await new RemoteServer({runtime,media,token}).listen(0,'127.0.0.1');
 t.after(async()=>{finishFirst();await server.close();await runtime.close();await fs.rm(dir,{recursive:true,force:true});});
 async function req(route,body,auth=token){const res=await fetch(server.url+route,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+auth,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:res.status,value:await res.json()};}
 assert.equal((await req('/v1/state',null,'wrong')).status,401);
 const session=(await req('/v1/session/start',{})).value;
 clock=200;
 const segment={sessionId:session.id,sequence:0,startMs:0,endMs:100,frames:[{atMs:0,data:'YQ=='}]};
 assert.equal((await req('/v1/segments',segment)).status,200);
 assert.equal((await req('/v1/segments',segment)).value.duplicate,true);assert.equal(assemblies,1);
 assert.equal((await req('/v1/segments',{...segment,endMs:200})).status,409);
 const a=(await req('/v1/questions',{sessionId:session.id,question:'first',anchorMs:100})).value;await invoked;
 const b=(await req('/v1/questions',{sessionId:session.id,question:'second',anchorMs:100})).value;
 let state=(await req('/v1/state')).value;
 assert.deepEqual(state.chat.jobs.map(j=>j.status),['running','queued']);
 assert.equal(state.chat.jobs[1].anchorMs,100);
 await req('/v1/questions/'+b.id+'/cancel',{});
 assert.equal((await req('/v1/state')).value.chat.jobs[0].status,'running');
 finishFirst();await runtime.deep.jobs[0].done;
 await req('/v1/session/pause',{});
 const resumed=(await req('/v1/session/start',{})).value;
 assert.equal(resumed.id,session.id);assert.equal((await req('/v1/state')).value.chat.jobs[0].result.answer,'first');
 assert.equal((await req('/v1/questions',{sessionId:'stale',question:'no',anchorMs:100})).status,400);
 clock=3000;
 assert.equal((await req('/v1/segments',{...segment,sequence:1,startMs:2100,endMs:2200,frames:[{atMs:2100,data:'YQ=='}]})).status,200);
 assert.deepEqual((await req('/v1/state')).value.captureGaps,[{startMs:100,endMs:2100}]);
 assert.equal((await req('/v1/segments',{...segment,sequence:1,endMs:9000})).status,400);
 const expiredBefore=await fetch(server.url+'/v1/media/moment-1',{headers:{Authorization:'Bearer '+token,Range:'bytes=0-2'}});
 assert.equal(expiredBefore.status,206);assert.equal(await expiredBefore.text(),'fix');
 clock=301000;await runtime.session.watch.prune();
 assert.equal((await req('/v1/media/moment-1')).status,410);
 assert.equal((await req('/v1/state')).value.chat.jobs[0].result.answer,'first','media expiry preserves conversation');
});
