const {test}=require('node:test'),assert=require('node:assert/strict');
const {SessionClock}=require('../core/session-clock.cjs');const {WatchSession}=require('../core/session.cjs');
const {CodexSessionAgent,streamedAnswer}=require('../adapters/codex-session-agent.cjs');
test('pause freezes observation time; resume keeps media IDs, memory, counters and chronology',async()=>{
 let wall=0;const clock=new SessionClock(()=>wall);const watch=new WatchSession({id:'s',now:()=>clock.now(),perception:{observe:async()=>({observation:{summary:'Remember me'},cost:0})},media:{put:async()=>{},read:async()=>({})},archive:{save:async()=>{}}});
 wall=1000;await watch.ingest({startMs:0,endMs:1000,frames:[]});await new Promise(r=>setImmediate(r));clock.pause();await watch.stop();wall=90000;
 assert.equal(watch.snapshot().elapsedMs,1000);assert.equal(watch.segments[0].observation.summary,'Remember me');clock.resume();await watch.resume();wall+=1000;await watch.ingest({startMs:1000,endMs:2000,frames:[]});assert.equal(watch.id,'s');assert.deepEqual(watch.segments.map(s=>s.id),['moment-1','moment-2']);assert.equal(watch.now(),2000);
});
test('one warm Codex thread handles successive turns, streams answer only and carries context deltas',async()=>{
 const requests=[],progress=[];let connects=0;const agent=new CodexSessionAgent({rpcFactory:options=>({start(){connects++;return this;},send(){},close(){},async request(method,params){requests.push({method,params});if(method==='thread/start')return {thread:{id:'thread-one'}};if(method==='turn/start'){const id='t'+requests.length;setImmediate(()=>{options.onEvent('turn/started',{threadId:'thread-one',turn:{id}});options.onEvent('item/started',{threadId:'thread-one',turnId:id,item:{type:'reasoning',text:'PRIVATE_REASONING'}});const answer=JSON.stringify({answer:'Jaune',kind:'observation',citations:[],limits:[],sources:[]});options.onEvent('item/agentMessage/delta',{threadId:'thread-one',turnId:id,delta:answer});options.onEvent('item/completed',{threadId:'thread-one',turnId:id,item:{type:'agentMessage',text:answer}});options.onEvent('turn/completed',{threadId:'thread-one',turn:{id,status:'completed'}});});return {turn:{id}};}return {};}})});
 const input={tools:{sessionId:'s',anchorMs:100},signal:AbortSignal.timeout(5000),context:{passages:[{id:'m',startMs:0,endMs:100,text:'Cercle jaune'}]},onProgress:p=>progress.push(p)};
 try{const first=await agent.answer({...input,question:'Couleur ?'});const second=await agent.answer({...input,question:'Répète'});assert.equal(first.threadId,second.threadId);assert.equal(connects,1);const turns=requests.filter(x=>x.method==='turn/start');assert.ok(turns[0].params.input[0].text.includes('Cercle jaune'));assert.ok(!turns[1].params.input[0].text.includes('Cercle jaune'));assert.ok(progress.some(p=>p.preview==='Jaune'));assert.ok(!JSON.stringify(progress).includes('PRIVATE_REASONING'));}finally{await agent.close();}
});
test('stream parser ignores raw schema and handles escaped answer fragments',()=>{assert.equal(streamedAnswer('{"answer":"Bonj'),'Bonj');assert.equal(streamedAnswer('{"citations":[]'), '');assert.equal(streamedAnswer('{"answer":"Une \\"citation'), 'Une "citation');});
test('embedding cache reuses identical descriptions across different moments and after reload',async()=>{
 const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');const {EmbeddingStore}=require('../adapters/embedding-store.cjs');const dir=await fs.mkdtemp(path.join(os.tmpdir(),'tvlens-embed-reuse-'));
 try{const file=path.join(dir,'cache.json');const cache=new EmbeddingStore(file,'model');await cache.put('moment-1','Same scene',[1,2]);assert.deepEqual(await cache.get('moment-2','Same scene'),[1,2]);assert.equal(await cache.get('moment-1','Changed scene'),null);assert.deepEqual(await new EmbeddingStore(file,'model').get('moment-3','Same scene'),[1,2]);assert.equal(await new EmbeddingStore(file,'other').get('moment-3','Same scene'),null);}finally{await fs.rm(dir,{recursive:true,force:true});}
});
test('interrupt keeps the same warm thread for the next question and does not deliver stale output',async()=>{
 let turns=0,connections=0,started;const firstStarted=new Promise(r=>started=r);
 const agent=new CodexSessionAgent({rpcFactory:options=>({start(){connections++;return this;},send(){},close(){},async request(method,params){if(method==='thread/start')return {thread:{id:'same-thread'}};if(method==='turn/interrupt'){options.onEvent('turn/completed',{threadId:'same-thread',turn:{id:params.turnId,status:'interrupted'}});return {};}
 if(method==='turn/start'){const id='turn-'+(++turns);setImmediate(()=>{options.onEvent('turn/started',{threadId:'same-thread',turn:{id}});if(turns===1){started();return;}const text=JSON.stringify({answer:'Nouvelle réponse',kind:'explanation',citations:[],sources:[],limits:[]});options.onEvent('item/completed',{threadId:'same-thread',turnId:id,item:{type:'agentMessage',text}});options.onEvent('turn/completed',{threadId:'same-thread',turn:{id,status:'completed'}});});return {turn:{id}};}return {};}})});
 try{const controller=new AbortController();const first=agent.answer({question:'Ancienne',tools:{sessionId:'s',anchorMs:100},signal:controller.signal});first.catch(()=>{});await firstStarted;controller.abort(Error('Annulée'));const second=agent.answer({question:'Nouvelle',tools:{sessionId:'s',anchorMs:100},signal:AbortSignal.timeout(5000)});await assert.rejects(first);const result=await second;assert.equal(result.answer,'Nouvelle réponse');assert.equal(result.threadId,'same-thread');assert.equal(connections,1);}finally{await agent.close();}
});
